# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rangetastic}
  s.version = "0.3.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Chris Herring"]
  s.date = %q{2009-11-20}
  s.description = %q{Filter dates for ActiveRecord using very simple _between syntax}
  s.email = %q{chris.herring.iphone@gmail.com}
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    ".gitignore",
     "MIT-License",
     "Manifest",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "lib/rangetastic.rb",
     "rangetastic.gemspec",
     "spec/fixtures/models.rb",
     "spec/fixtures/structure.sql",
     "spec/rangetastic_spec.rb",
     "spec/spec_helper.rb",
     "spec/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/cherring/rangetastic}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Simple filtering by date ranges for ActiveRecord}
  s.test_files = [
    "spec/fixtures/models.rb",
     "spec/rangetastic_spec.rb",
     "spec/spec_helper.rb",
     "spec/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

